enum Category {
  FOOD = "FOOD",
  BEVERAGE = "BEVERAGE",
  JUNKFOOD = "JUNKFOOD",
  SPORTS = "SPORTS",
  TRAVEL = "TRAVEL",
  ELECTRONICS = "ELECTRONICS",
  RESTAURANTS = "RESTAURANTS",
  VACATION = "VACATION",
  CLOTHING = "CLOTHING",
  SHOES = "SHOES",
  OTHERS = "OTHERS",
}

export default Category;